name: qlora_blip2
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.8.6
  - aiosignal=1.3.1
  - async-timeout=4.0.3
  - attrs=23.1.0
  - aws-c-auth=0.7.6
  - aws-c-cal=0.6.9
  - aws-c-common=0.9.8
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.2
  - aws-c-http=0.7.14
  - aws-c-io=0.13.35
  - aws-c-mqtt=0.9.9
  - aws-c-s3=0.3.23
  - aws-c-sdkutils=0.1.12
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.24.6
  - aws-sdk-cpp=1.11.182
  - blas=1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.21.0
  - ca-certificates=2023.08.22
  - certifi=2023.7.22
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - dataclasses=0.8
  - datasets=2.14.6
  - dill=0.3.7
  - filelock=3.13.1
  - frozenlist=1.4.0
  - fsspec=2023.10.0
  - gflags=2.2.2
  - glog=0.6.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - huggingface_hub=0.17.3
  - icu=73.2
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - intel-openmp=2022.1.0
  - jinja2=3.1.2
  - joblib=1.3.2
  - krb5=1.21.2
  - libabseil=20230802.1
  - libarrow=14.0.1
  - libarrow-acero=14.0.1
  - libarrow-dataset=14.0.1
  - libarrow-flight=14.0.1
  - libarrow-flight-sql=14.0.1
  - libarrow-gandiva=14.0.1
  - libarrow-substrait=14.0.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.4.0
  - libcxx=16.0.6
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libgoogle-cloud=2.12.0
  - libgrpc=1.59.2
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libnghttp2=1.58.0
  - libopenblas=0.3.24
  - libparquet=14.0.1
  - libprotobuf=4.24.4
  - libre2-11=2023.06.02
  - libsqlite=3.41.2
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libutf8proc=2.8.0
  - libxml2=2.11.5
  - libzlib=1.2.13
  - llvm-openmp=17.0.4
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - mkl=2022.1.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - multidict=6.0.4
  - multiprocess=0.70.15
  - ncurses=6.4
  - networkx=3.1
  - numpy=1.26.0
  - openssl=3.1.4
  - orc=1.9.0
  - packaging=23.2
  - pandas=2.1.3
  - pip=23.3.1
  - pyarrow=14.0.1
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python-xxhash=3.4.1
  - python_abi=3.10
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - re2=2023.06.02
  - readline=8.2
  - regex=2023.10.3
  - requests=2.31.0
  - sacremoses=0.0.53
  - safetensors=0.3.3
  - setuptools=68.0.0
  - six=1.16.0
  - snappy=1.1.10
  - sqlite=3.41.2
  - sympy=1.11.1
  - tbb=2021.10.0
  - tk=8.6.12
  - tokenizers=0.14.1
  - tqdm=4.66.1
  - transformers=4.35.0
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - tzdata=2023c
  - urllib3=2.1.0
  - wheel=0.41.2
  - xxhash=0.8.2
  - xz=5.4.2
  - yaml=0.2.5
  - yarl=1.9.2
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - accelerate==0.24.1
      - contourpy==1.2.0
      - cycler==0.12.1
      - fonttools==4.44.1
      - kiwisolver==1.4.5
      - matplotlib==3.8.1
      - opencv-python-headless==4.8.1.78
      - peft==0.6.2
      - pillow==10.1.0
      - psutil==5.9.6
      - pycocotools==2.0.7
      - pyparsing==3.1.1
      - scikit-learn==1.3.2
      - scipy==1.11.3
      - threadpoolctl==3.2.0
      - torch==2.2.0.dev20231114
      - torchaudio==2.2.0.dev20231114
      - torchvision==0.17.0.dev20231114
      - vision-evaluation==0.2.14
