name: qlora_blip2
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.12
  - pip=23.3
  - python=3.10.13
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - accelerate==0.24.1
      - bitsandbytes==0.41.2.post2
      - certifi==2023.7.22
      - charset-normalizer==3.3.2
      - filelock==3.13.1
      - fsspec==2023.10.0
      - huggingface-hub==0.19.4
      - idna==3.4
      - jinja2==3.1.2
      - markupsafe==2.1.3
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.26.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - packaging==23.2
      - peft==0.6.2
      - pillow==10.1.0
      - psutil==5.9.6
      - pyyaml==6.0.1
      - regex==2023.10.3
      - requests==2.31.0
      - safetensors==0.4.0
      - sympy==1.12
      - tokenizers==0.15.0
      - torch==2.1.1
      - torchaudio==2.1.1
      - torchvision==0.16.1
      - tqdm==4.66.1
      - transformers==4.35.2
      - triton==2.1.0
      - typing-extensions==4.8.0
      - urllib3==2.1.0
