name: qlora_blip2
channels:
  - conda-forge
  - defaults
dependencies:
  - libbrotlidec=1.1.0
  - urllib3=2.1.0
  - python-dateutil=2.8.2
  - libthrift=0.19.0
  - libxml2=2.11.5
  - libarrow-acero=14.0.1
  - libarrow-gandiva=14.0.1
  - numpy=1.26.0
  - libre2-11=2023.06.02
  - yarl=1.9.2
  - yaml=0.2.5
  - huggingface_hub=0.17.3
  - aws-c-event-stream=0.3.2
  - aws-c-cal=0.6.9
  - icu=73.2
  - regex=2023.10.3
  - pandas=2.1.3
  - pyarrow=14.0.1
  - aiohttp=3.8.6
  - glog=0.6.0
  - liblapack=3.9.0
  - async-timeout=4.0.3
  - pyyaml=6.0.1
  - mpfr=4.0.2
  - packaging=23.2
  - sacremoses=0.0.53
  - aws-crt-cpp=0.24.6
  - libssh2=1.11.0
  - libcblas=3.9.0
  - markupsafe=2.1.1
  - mpmath=1.3.0
  - libev=4.33
  - brotli-python=1.1.0
  - libutf8proc=2.8.0
  - libarrow-flight-sql=14.0.1
  - libcrc32c=1.1.2
  - six=1.16.0
  - mkl=2022.1.0
  - libzlib=1.2.13
  - python-xxhash=3.4.1
  - aws-sdk-cpp=1.11.182
  - zipp=3.17.0
  - sympy=1.11.1
  - safetensors=0.3.3
  - frozenlist=1.4.0
  - xxhash=0.8.2
  - zstd=1.5.5
  - sqlite=3.41.2
  - libgrpc=1.59.2
  - idna=3.4
  - tzdata=2023c
  - typing_extensions=4.8.0
  - libprotobuf=4.24.4
  - jinja2=3.1.2
  - libffi=3.4.4
  - aws-c-http=0.7.14
  - libarrow=14.0.1
  - multiprocess=0.70.15
  - aws-c-mqtt=0.9.9
  - lz4-c=1.9.4
  - libedit=3.1.20191231
  - libcurl=8.4.0
  - re2=2023.06.02
  - mpc=1.1.0
  - snappy=1.1.10
  - libopenblas=0.3.24
  - requests=2.31.0
  - gmpy2=2.1.2
  - python_abi=3.10
  - zlib=1.2.13
  - ca-certificates=2023.08.22
  - aws-c-compression=0.2.17
  - llvm-openmp=17.0.4
  - dataclasses=0.8
  - pytorch=2.1.0
  - filelock=3.13.1
  - openssl=3.1.4
  - multidict=6.0.4
  - libbrotlienc=1.1.0
  - gmp=6.2.1
  - networkx=3.1
  - libevent=2.1.12
  - blas=1.0
  - libiconv=1.17
  - xz=5.4.2
  - typing-extensions=4.8.0
  - aws-checksums=0.1.17
  - tk=8.6.12
  - colorama=0.4.6
  - aws-c-s3=0.3.23
  - transformers=4.35.0
  - c-ares=1.21.0
  - bzip2=1.0.8
  - importlib-metadata=6.8.0
  - ncurses=6.4
  - libnghttp2=1.58.0
  - datasets=2.14.6
  - aws-c-io=0.13.35
  - krb5=1.21.2
  - attrs=23.1.0
  - wheel=0.41.2
  - tokenizers=0.14.1
  - libbrotlicommon=1.1.0
  - libabseil=20230802.1
  - click=8.1.7
  - libcxx=16.0.6
  - libgoogle-cloud=2.12.0
  - libarrow-substrait=14.0.1
  - libarrow-flight=14.0.1
  - certifi=2023.7.22
  - aws-c-auth=0.7.6
  - aws-c-common=0.9.8
  - setuptools=68.0.0
  - importlib_metadata=6.8.0
  - python-tzdata=2023.3
  - readline=8.2
  - libgfortran=5.0.0
  - dill=0.3.7
  - aws-c-sdkutils=0.1.12
  - fsspec=2023.10.0
  - pip=23.3
  - gflags=2.2.2
  - orc=1.9.0
  - intel-openmp=2022.1.0
  - pysocks=1.7.1
  - pytz=2023.3.post1
  - libllvm15=15.0.7
  - charset-normalizer=3.3.2
  - libgfortran5=13.2.0
  - joblib=1.3.2
  - libblas=3.9.0
  - tqdm=4.66.1
  - libarrow-dataset=14.0.1
  - aiosignal=1.3.1
  - libparquet=14.0.1
  - python=3.10.13
